binary: buildconfig
dependencies:
- name: make
- name: awk
- name: sed
- name: ginkgo
  version_check:
    command: version | ${tools[awk]} '{print $3}'
    min_version: 1.10
- name: go
  version_check:
    min_version: 1.12
    command: version | ${tools[awk]} '{where = match($0, /[0-9]\.[0-9]+[\.0-9]*/); if (where != 0) print substr($0, RSTART, RLENGTH)}'
- name: golangci-lint
